version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aim-backend-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pw82a1troeol"
s3_prefix = "aim-backend-challenge"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
