AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aim-backend-challenge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName

Parameters:
  StageName:
    Type: String
    Default: "dev"
    Description: (Required) Enter dev, prod. Default is dev.
    AllowedValues:
      - "dev"
      - "prod"
  TableName:
    Type: String
    Default: "aimDevTable"
    AllowedValues:
      - "aimDevTable"
      - "aimProdTable"
    Description: DynamoDB Table Name

Resources:
  AimAPI:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      StageName: !Ref StageName

  CreateDeveloper:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/createDeveloper
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CreateDev:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /developers
            Method: post
            RestApiId: !Ref AimAPI
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts

  GetDeveloperInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/getDeveloperInfo
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        GetDevInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /developers/{username}
            Method: get
            RestApiId: !Ref AimAPI
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts

Outputs:
  AimBackendApi:
    Description: "API Gateway endpoint URL for Aim Backend API"
    Value: !Sub "https://${AimAPI}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
